[profile.default]
src = 'contracts'
out = 'foundry_artifacts'
libs = ["node_modules", "lib"]
gas_reports = ["*"]
memory_limit = 11149934592
fs_permissions = [{access = "read", path = "./test/uarch-log/"}, {access = "read", path = "./test/uarch-bin/"}]
remappings = [
    '@cartesi/=node_modules/@cartesi/',
    '@ensdomains/=node_modules/@ensdomains/',
    '@openzeppelin/=node_modules/@openzeppelin/',
    'eth-gas-reporter/=node_modules/eth-gas-reporter/',
    'hardhat-deploy/=node_modules/hardhat-deploy/',
    'hardhat/=node_modules/hardhat/',
]

[fmt]
line_length = 80
ignore = ["test/UArchReplay_*"]
tab_width = 4
