name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly-7545c7a2857a873fa1909ec4174032c4e4702116

      - run: forge build
      - run: forge fmt --check
