name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install gpp
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: gpp
          version: 2.27

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly-5be158ba6dc7c798a6f032026fe60fc01686b33b

      - name: Run all tests
        run: make test-all
