name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install gpp
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: gpp
          version: 2.27

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly-008922d5165c764859bc540d7298045eebf5bc60

      - name: Run all tests
        run: make test-all
